version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml  
      - prometheus_data:/prometheus  
    ports:
            - '9090'
    networks:
      monitoring:
        ipv4_address: 192.168.32.2

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      monitoring:
        ipv4_address: 192.168.32.3

  node_exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
       - "9100"
    networks:
      monitoring:
        ipv4_address: 192.168.32.4
    command: [
      "--web.listen-address=:9100",
      "--path.procfs=/host/proc",
      "--path.sysfs=/host/sys",
      "--path.rootfs=/host"
    ]
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro

  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml  
    ports:
      - '9093'  
    networks:
      monitoring:
        ipv4_address: 192.168.32.5

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.32.0/24

volumes:
  grafana-data:
  prometheus_data:  
