global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'  # Использует имя сервиса из docker-compose

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - { targets: ['*******60:9100'], labels: { server: 'Server-1' } }
      - { targets: ['*******20:9100'], labels: { server: 'Server-2' } }


  - job_name: 'mysqld_exporter'
    static_configs:
      - { targets: ['*******60:9104'], labels: { server: 'Server-1' } }
      - { targets: ['*******20:9104'], labels: { server: 'Server-2' } }
     